### ISSUE TITLE
Stomp should not be a dependency for all Stapfen workers

### ISSUE THREAD

**Issue by blaines** [lookout/stapfen#30]
Stomp is required in stapfen/worker.rb but it's unnecessary because it should have already been loaded 
Here: https://github.com/lookout/stapfen/blob/master/lib/stapfen.rb#L2
or here: https://github.com/lookout/stapfen/blob/master/lib/stapfen/worker.rb#L44

I've removed this line in my pull request,
https://github.com/lookout/stapfen/blob/master/lib/stapfen/worker.rb#L1

This change shouldn't affect older dependent applications.

**Comment by rtyler** [comment]
Fixed by #32
