### ISSUE TITLE
module Stapfen::Logger should be optional or have a more specific use case

### ISSUE THREAD

**Issue by blaines** [lookout/stapfen#37]
I'm having issues using logback with Stapfen. I've tried a few ways, all of which are hackish due to the fact that the Stapfen::Logger requires the "logger" attribute to be a Proc and all the proxy methods (info, debug, warn, etc) "call" the proc.

I have some ideas:
- Rename the logger attribute to indicate Stapfen-specific application (logger_proc)
- Remove the logger module entirely, as it doesn't serve a purpose to Stapfen itself (compare to something like Faraday, and it's logger)
- Refactor the logger to use a Proc

https://github.com/lookout/stapfen/blob/master/lib/stapfen/logger.rb#L21
https://github.com/lookout/stapfen/blob/master/lib/stapfen/worker.rb#L109

**Comment by rtyler** [comment]
I think the right way forward here might be to break some API compatibility, bump the major version and remove the log block and replace it with the `before` block we discussed IRL

**Comment by rtyler** [comment]
I believe this can be closed now
